Imaz_Rosshandler_marker_genes <- list(
  "Allantois" = c("Hoxa10", "Hoxa11", "Tbx2", "Tbx4"),
  "Allantois endothelium" = c("Cdh5", "Hoxa11", "Plac1", "Vcam1"),
  "Amniotic ectoderm" = c("Aqp2", "Hand1", "Lrrn4", "Msx1", "Msx2", "Tagln", "Tfap2a", "Vtcn1", "Wnt6", "Wt1"),
  "Anterior cardiopharyngeal progenitors" = c("Isl1", "Tcf21", "Tlx1"),
  "Anterior Primitive Streak" = c("Fgf8", "Foxa2", "Gsc", "Hhex", "Lhx1", "Mixl1", "Otx2", "Pax7"),
  "Anterior somitic tissues" = c("Arg1", "Id2", "Id3", "Irx3", "Marcks", "Meis2", "Meox1", "Mest", "Pax1", "Pax9", "Prrx2", "Sox9", "Tcf15"),
  "Blood progenitors" = c("Cited4", "Gata1", "Lmo2", "Runx1"),
  "Branchial arch neural crest" = c("Dlx1", "Dlx2", "Dlx3", "Dlx4", "Dlx5", "Dlx6", "Hoxa2", "Mef2c"),
  "Cardiomyocytes FHF 1" = c("Gata4", "Nkx2-5", "Nr2f2", "Osr1", "Tbx5", "Wnt2"),
  "Cardiomyocytes FHF 2" = c("Gata4", "Nkx2-5", "Nr2f2", "Osr1", "Tbx5", "Wnt2"),
  "Cardiomyocytes SHF 1" = c("Fgf10", "Fgf3", "Fgf8", "Isl1", "Itbp3", "Mef2c", "Tbx1", "Tlx1"),
  "Cardiomyocytes SHF 2" = c("Fgf10", "Fgf3", "Fgf8", "Isl1", "Itbp3", "Mef2c", "Nrp2", "Tbx1", "Tbx5", "Tlx1", "Wnt2"),
  "Cardiopharyngeal progenitors" = c("Mesp1", "Nr2f2", "Osr1", "Tbx5", "Wnt2", "Wt1"),
  "Cardiopharyngeal progenitors FHF" = c("Smarcd3"),
  "Cardiopharyngeal progenitors SHF" = c("Isl1", "Tcf21", "Tlx1"),
  "Caudal epiblast" = c("Nkx1-2"),
  "Caudal mesoderm" = c("Cdx1", "Cdx2", "Gbx2", "Hes7", "Hoxb1"),
  "Chorioallantoic-derived erythroid progenitors" = c("Abcb4", "Gata1", "Hba-x", "Hbb-bs", "Hbb-bt", "Hbb-y", "Kel", "Klf1", "Myb", "Slc4a1", "Sox6"),
  "Cranial mesoderm" = c("Apoe", "Ebf1", "Foxl2", "Id2", "Id3", "Irx3", "Myl9", "Ndufa4l2", "Pitx2", "Six1"),
  "Dermomyotome" = c("Aldh1a2", "Cadm1", "Dmrt2", "Meis2", "Meox1", "Meox2", "Myf5", "Pax3", "Snail2"),
  "Dorsal hindbrain progenitors" = c("Msx1", "Msx3", "Wn1", "Zic1", "Zic2", "Zic5"),
  "Dorsal midbrain neurons" = c("Ascl1", "Dll3", "Elavl3", "Elavl4", "Gadd45g", "Hes6", "Neurod4", "Neurog1"),
  "Dorsal spinal cord progenitors" = c("Hoxb2", "Hoxd4", "Msx1", "Pax3", "Pax6", "Zic1"),
  "Early dorsal forebrain progenitors" = c("Fgf17", "Fgf8", "Lhx2", "Mest", "Otx2", "Six3", "Six6"),
  "Ectoderm" = c("Otx2", "Pou3f1", "Pou5f1", "Sox2"),
  "Embryo proper endothelium" = c("Cdh5", "Crabp2", "Etv2", "Fev", "Hoxa2", "Chd5", "Pecam1", "Dlk1", "Meg3"),
  "Embryo proper mesothelium" = c("Acta2", "Aldh1a2", "Ctgf", "Eng", "Fn1", "Gata4", "Gpm6a", "Mef2c", "Pdgfra", "Pdgfrb", "Postn", "Tbx18", "Tbx5", "Tcf21", "Upk1b", "Upk3b", "Vim", "Wt1"),
  "EMP" = c("Csf1r", "Kit", "Myb", "Runx1"),
  "Endocardium" = c("Nkx2-5", "Pecam1", "Sox17", "Vwf", "Id1", "Id3", "Hey"),
  "Endotome" = c("Cxcl12", "Pax3", "Meox1", "Foxc2", "Pdgfra", "Alcam", "Hlf"),
  "Epiblast" = c("Dnmt3b", "Epcam", "Pou5f1", "Utf1"),
  "Epicardium" = c("Aldh1a2", "Bnc1", "Itga4", "Krt8", "Scx", "Sema3d", "Sfrp", "Sparc", "Tbx18", "Tcf21", "Upk3b", "Vcam1", "Wt1"),
  "Epidermis" = c("Hapln1", "Krt14", "Krt5", "Sfn", "Trp63", "Wnt4"),
  "Erythroid" = c("Abcb4", "Gata1", "Hba-x", "Hbb-bs", "Hbb-bt", "Hbb-y", "Kel", "Klf1", "Myb", "Slc4a1", "Sox6"),
  "ExE ectoderm" = c("Ascl2", "Elf5", "Tfap2c"),
  "ExE endoderm" = c("Apoa2", "Apoe1", "Cystm1", "Emb", "Ttr"),
  "Foregut" = c("Foxa1", "Foxa2", "Gata6", "Hhex", "Hnf4a", "Hoxa1", "Irx1", "Prox1", "Ripply3", "Sfrp5", "Tbx3", "Ttr"),
  "Forelimb" = NA,
  "Frontonasal mesenchyme" = c("Alx1", "Alx3", "Alx4", "Prrx1", "Twist1"),
  "Gut tube" = c("Apela", "Foxa2", "Sox17", "Spink1"),
  "Haematoendothelial progenitors" = c("Etv2", "Kdr"),
  "Hindbrain floor plate" = c("Foxa2", "Nkx2-9", "Nkx6-1", "Ntn1", "Shh"),
  "Hindbrain neural progenitors" = c("Hes5", "Hoxb4", "Hoxd4", "Olig2", "Pax6"),
  "Hindgut" = c("Cdx2", "Cdx4", "Foxa2", "Hoxa7", "Hoxb8", "Hoxc8", "Shh", "Sox17", "Sp5"),
  "Intermediate mesoderm" = c("Osr1"),
  "Kidney primordium" = c("Eya1", "Gata3", "Hoxd11", "Lhx1", "Nrp1", "Osr1", "Pax2", "Pax8", "Sall1", "Sox11"),
  "Late dorsal forebrain progenitors" = c("Id3", "Pax6", "Rspo2", "Rspo3", "Wnt8b"),
  "Lateral plate mesoderm" = c("Cdx2", "Cdx4", "Foxf1", "Fzd4", "Kdr"),
  "Limb ectoderm" = NA,
  "Limb mesoderm" = c("Hand1", "Hand2", "Lbx1", "Pax7", "Pitx1", "Prrx1", "Tbx4", "Tbx5"),
  "Megakaryocyte progenitors" = c("Itga2b", "Mpl", "Myl9", "Pf4", "Plek", "Ppbp", "Runx1", "Treml1", "Vwf"),
  "MEP" = c("Cd34", "Gata1", "Gata2", "Itga2b", "Klf1", "Mpl", "Plek", "Runx1", "Vwf"),
  "Mesenchyme" = c("Ahnak", "Bmp4", "Col3a1", "Dlk1", "Igf2", "Itga4", "Krt18", "Krt8", "Lgals1", "Pmp22"),
  "Midbrain progenitors" = c("Pax6", "Sp5"),
  "Midbrain/Hindbrain boundary" = c("En1", "En2", "Fgf8", "Gbx2", "Otx2", "Pax2", "Pax5", "Pax8", "Wnt1"),
  "Midgut" = c("Gata6", "Nepn"),
  "Migratory neural crest" = c("Foxd3", "Pax3", "Sox10", "Sox9", "Tfap2b"),
  "Nascent mesoderm" = c("Lefty2", "Mesp1", "Mesp2"),
  "Neural tube" = c("Cdx2", "Cdx4", "Hoxa7", "Hoxa9", "Hoxaas3", "Hoxb2", "Hoxb5os", "Hoxb8", "Hoxc8", "Hoxc9", "Nkx1-2"),
  "NMPs" = c("Cdx1", "Cdx2", "Cdx4", "Cyp26a1", "Epha5", "Fgf17", "Fgf8", "Hes3", "Hoxb9", "Nkx1-2", "Rspo3", "T"),
  "NMPs/Mesoderm-biased" = c("Cdx1", "Cdx2", "Cdx4", "Cyp26a1", "Fgf17", "Fgf8", "Nkx1-2", "Rspo3", "T"),
  "Node" = c("Chrd", "Dynlrb2", "Foxa2", "Foxj1", "Noto", "Pifo", "T"),
  "Non-neural ectoderm" = c("Bmp2", "Cxcl12", "Dkk1", "Dlk1", "Krt genes", "Krt18", "Krt19", "Krt7", "Krt8", "Msx genes", "Msx2", "Mt1", "Mt2", "Pdgfa", "Tfap2a", "Tfap2b", "Wnt4", "Wnt6"),
  "Notochord" = c("Bicc1", "Foxa2", "Nog", "Noto", "Shh", "T"),
  "Optic vesicle" = c("Foxd1", "Lhx2", "Otx2", "Pax6", "Rax", "Six6"),
  "Otic neural progenitors" = c("Eya2", "Isl1", "Neurod1", "Neurog1", "Six1"),
  "Otic placode" = c("Dlx5", "Lmx1a", "Pax8", "Six1", "Sox9", "Tbx2"),
  "Paraxial mesoderm" = c("Meox1", "Tbx1", "Tcf15"),
  "Parietal endoderm" = c("Lamb1", "Plat", "Sparc"),
  "PGC" = c("Dnd1", "Dppa3", "Ifitm3", "Nanos3", "Pou5f1", "Tfap2c"),
  "Pharyngeal endoderm" = c("Fgf8", "Isl1", "Meis2", "Nkx2-3", "Prrx2", "Six1"),
  "Pharyngeal mesoderm" = c("Isl1", "Tcf21"),
  "Placodal ectoderm" = c("Dlx5", "Dlx6", "Foxg1", "Otx2", "Pitx1", "Six1", "Six3", "Six6", "Sox2"),
  "Posterior somitic tissues" = c("Cadm1", "Dll3", "Hes7", "Laptm4b", "Lef1", "Pcdh19", "Slc9a3r1"),
  "Presomitic mesoderm" = c("Msgn1", "T", "Tbx6"),
  "Primitive Streak" = c("Eomes", "Nanog"),
  "Sclerotome" = c("Aldh1a2", "Meis2", "Meox1", "Myf5"),
  "Somitic mesoderm" = c("Aldh1a2", "Dll1", "Tbx6"),
  "Spinal cord progenitors" = c("Cdx1", "Cdx2", "Cdx4", "Hoxa10", "Hoxa3", "Hoxa9", "Hoxaas3", "Hoxb1", "Hoxb4", "Hoxb5", "Hoxb5os", "Hoxb8", "Hoxb9", "Hoxc10", "Hoxc6", "Hoxc8", "Hoxc9", "Hoxd4", "Ncam1", "Nkx1-2", "Nkx2-1", "Pax6", "Sox2", "T"),
  "Surface ectoderm" = c("Foxg1", "Grhl2", "Grhl3", "Trp63"),
  "Thyroid primordium" = c("Foxa2", "Foxe1", "Ltbp1", "Nkx2-1", "Nkx2-5", "Pax8", "Sox2"),
  "Venous endothelium" = c("Cdh5", "Ephb4", "Foxc1", "Foxc2", "Hoxa4", "Nr2f2", "Prox1", "Zic2", "Mef2c", "Clec1b", "Cldn5"),
  "Ventral forebrain progenitors" = c("Lhx2", "Lhx5", "Nkx2-1", "Nkx2-9", "Ptch1", "Shh"),
  "Ventral hindbrain progenitors" = c("Foxb1", "Hoxa2", "Hoxd4", "Nkx2-9", "Nkx6-1", "Nkx6-2", "Olig2", "Sfrp1", "Sfrp2"),
  "Visceral endoderm" = c("Amot", "Dkk1", "Emb", "Krt19", "Spink1", "Ttr"),
  "YS endothelium" = c("Anxa2", "Cdh5", "Itga4", "Lgals1", "Sparc", "Lyve1"),
  "YS mesothelium" = c("Hoxc8", "Lum"),
  "YS mesothelium-derived endothelial progenitors" = c("Anxa2", "Cdh5", "Itga4", "Lgals1", "Sparc")
)

Harland_marker_genes_list <- list(
  
  # Early Gastrula (Listed First)
  "Anterior Primitive Streak" = c("Gsc", "Foxa2"),  
  "Parietal endoderm" = c("Sox7", "Pdgfra"),  
  "Gut tube" = c("Apela", "Foxa2"),  
  "ExE endoderm" = c("Ttr", "Apoa2"),  
  "Visceral endoderm" = c("Spink1", "Emb"),  
  "ExE ectoderm distal" = c("Ascl2", "Gjb3"),  
  "ExE ectoderm proximal" = c("Elf5", "Perp"),  
  "Epiblast" = c("Pou5f1", "Utf1"),  
  "Primitive Streak" = c("Nanog", "T"),  
  "Nascent mesoderm" = c("Lefty2", "Mixl1"),  
  "PGC" = c("Ifitm3", "Pou5f1"),  
  "ExE mesoderm" = c("Bmp4", "Foxf1"),  
  "Haematoendothelial progenitors" = c("Etv2", "Kdr"),  
  "Blood progenitors" = c("Cited4", "Gata1"),  
  "ExE mesoderm and Anterior LPM" = c("Pmp22", "Foxf1"),  
  "Non-neural ectoderm" = c("Msx2", "Cxcl12"),  
  "Ectoderm" = c("Otx2", "Pou3f1"),  
  "Intermediate mesoderm" = c("Tbx6", "Osr1"),  
  "Caudal epiblast" = c("Cdx1", "Nkx1-2"),  
  "Rostral ectoderm" = c("Sox2", "Otx2"),  

  # Endoderm
  "Foregut" = c("Foxa2", "Gata6"),  
  "Hindgut" = c("Cdx2", "Foxa2"),  
  "Pharyngeal endoderm" = c("Nkx2-3", "Fgf8"),  
  "Thyroid primordium" = c("Foxe1", "Nkx2-5"),  
  "Notochord" = c("Noto", "Shh"),  
  "Node" = c("T", "Noto"),  

  # LPM
  "Pharyngeal mesoderm" = c("Isl1","Tcf21"),
  "Anterior cardiopharyngeal progenitors" = c("Isl1", "Tlx1"), ## Tlx1 isn't found in seqFISH imputed markers list
  "Cardiopharyngeal progenitors FHF" = c("Smarcd3", "Tbx5"),  ## Tbx5 isn't found in seqFISH imputed markers list
  "Cardiomyocytes FHF 1" = c("Gata4", "Nkx2-5"),  
  "Cardiomyocytes FHF 2" = c("Gata4", "Wnt2"),  
  "Cardiomyocytes SHF 1" = c("Fgf8", "Isl1"),  
  "Epicardium" = c("Wt1", "Tcf21"),  ## Wt1 and Tcf21 aren't found in seqFISH imputed markers list
  "ExE mesoderm and Posterior LPM" = c("Cdx2", "Pitx1"),  
  "Anterior LPM" = c("Foxf1", "Aldh1a2"),  
  "Limb mesoderm" = c("Prrx1", "Hand2"),  
  "Kidney primordium" = c("Lhx1", "Osr1"),  
  "Allantois" = c("Tbx4", "Hoxa10"),  

  # Cranial Somitic
  "Paraxial mesoderm" = c("Tbx6", "Msgn1"),  
  "Presomitic mesoderm" = c("Msgn1", "Tbx6"),  
  "Somitic mesoderm" = c("Dll1", "Meox1"),  
  "Anterior somitic tissues" = c("Prrx2", "Marcks"),  
  "Posterior somitic tissues" = c("Meox2", "Arg1"),  
  "Dermomyotome" = c("Aldh1a2", "Pax3"),  
  "Endotome" = c("Cxcl12", "Foxc2"),  
  "Sclerotome" = c("Meox1", "Pax1"),  
  "Embryo proper mesothelium" = c("Pdgfrb", "Ppp1r14a"),  
  "Mesenchyme" = c("Bmp4", "Dlk1"),  
  "Cranial mesoderm" = c("Pitx2", "Six1"),  
  "Frontonasal mesenchyme" = c("Prrx1", "Twist1"),
  "NMPs" = c("T","Rspo3"),

  # Hematovascular
  "Allantois endothelium" = c("Plac1", "Bambi"),  
  "Embryo proper endothelium #1" = c("Cdh5", "Esam"),  
  "Embryo proper endothelium #2" = c("Ptn", "Ebf1"),  
  "Endocardium #1" = c("Pecam1", "Vwf"),  
  "Endocardium #2" = c("Kdr", "Gata5"),  
  "Haematoendothelial progenitors" = c("Etv2", "Kdr"),  
  "Blood progenitors" = c("Gata1", "Lmo2"),  
  "Erythroid" = c("Klf1", "Hbb-bs"),  
  "Chorioallantoic-derived erythroid progenitors" = c("Hbb-bs", "Slc4a1"),  
  "EMP" = c("Spi1", "Lyl1"),  
  "MEP" = c("Itga2b", "Mpl"),  

  # Neural Tube
  "Neural tube" = c("Sox2", "Pax6"),  
  "Optic vesicle" = c("Rax", "Otx2"),  
  "Ventral forebrain progenitors" = c("Nkx2-9", "Shh"),  
  "Midbrain progenitors" = c("Sp5", "Irx5"),  
  "Dorsal midbrain neurons" = c("Dll3", "Elavl4"),  
  "Midbrain/Hindbrain boundary" = c("En1", "Fgf8"),  
  "Dorsal hindbrain progenitors" = c("Msx1", "Zic1"),  
  "Hindbrain floor plate" = c("Foxa2", "Nkx6-1"),  
  "Hindbrain neural progenitors" = c("Hes5", "Pax6"),  
  "Ventral hindbrain progenitors" = c("Foxb1", "Nkx2-9"),  
  "Dorsal spinal cord progenitors" = c("Hoxb2", "Pax3"),  
  "Spinal cord progenitors" = c("Cdx1", "Hoxb1"),
    
  # Surface Ectoderm  
  "Amniotic ectoderm" = c("Wnt6", "Tfap2a"),
  "Surface ectoderm" = c("Trp63", "Grhl2"), ## both aren't found in seqFISH imputed markers list
  "Epidermis" = c("Wnt6", "Hapln1"), ## Wnt6 is not listed in Imaz_Rosshandler, Wnt4 is
  "Placodal ectoderm" = c("Dlx5", "Six1"),
  "Otic placode" = c("Pax8", "Sox9"), ## Pax8 is not found in seqFISH imputed markers list
  "Otic neural progenitors" = c("Eya2", "Isl1"),
  "Migratory neural crest" = c("Foxd3", "Sox9"),
  "Branchial arch neural crest" = c("Dlx1", "Mef2c"), ## both aren't found in seqFISH imputed markers list
  "Ectoderm" = c("Otx2", "Pou3f1"),
  "Non-neural ectoderm" = c("Msx2", "Wnt6")
  #"Limb ectoderm" = c("", "")
)